### 测试返回失败
GET http://127.0.0.1:9501/index/info/a
Accept: application/json
X-Language: en

###
GET http://127.0.0.1:9501/index/info/0
Accept: application/json
X-Language: ja

### 测试返回成功
GET http://127.0.0.1:9501/index/info/1
Accept: application/json
X-Language: ja


### 测试app/Utils/Functions.php convert_size
GET http://127.0.0.1:9501/index/test

### 测试不使用协程上下文的例子 a=1 输出"a": "1"或其他值 a 的输出值比较混乱
GET http://127.0.0.1:9501/index/demo?a=1

### 测试使用协程上下文的例子 a=1 输出"a": "1"
GET http://127.0.0.1:9501/index/demo1?a=1

### 测试数据库
GET http://127.0.0.1:9501/index/demodb

### 邮件发送注册
POST http://127.0.0.1:9501/auth/send-code?email=123@qq.com&scene=register
Accept: application/json
X-Language: ja

### 邮件发送登陆
POST http://127.0.0.1:9501/auth/send-code?email=123@qq.com&scene=login
Accept: application/json
X-Language: ja

### 验证邮件
POST http://127.0.0.1:9501/auth/login?email=123@qq.com&code=103369
Accept: application/json
X-Language: ja

### 注册用户
POST http://127.0.0.1:9501/auth/signup?email=123@qq.com&code=103369&password=123456&password_confirmation=123456
Accept: application/json
X-Language: ja

### 登陆用户
POST http://127.0.0.1:9501/auth/login?email=123@qq.com&password=123456
Accept: application/json
X-Language: ja

### 退出登陆
POST http://127.0.0.1:9501/auth/logout
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJoeXBlcmYtYXBpIiwiaWF0IjoxNzcyMjU1NjY1LCJleHAiOjE3NzIyNjI4NjUsInVpZCI6MX0.SwQM-i7JMiY-NWPxrTUR8N6NxSIu-DBnAv__JB2Z9_k
X-Language: ja