### 测试返回失败
GET http://127.0.0.1:9501/index/info/a
Accept: application/json
X-Language: en

###
GET http://127.0.0.1:9501/index/info/0
Accept: application/json
X-Language: ja

### 测试返回成功
GET http://127.0.0.1:9501/index/info/1
Accept: application/json
X-Language: ja


### 测试app/Utils/Functions.php convert_size
GET http://127.0.0.1:9501/index/test

### 测试不使用协程上下文的例子 a=1 输出"a": "1"或其他值 a 的输出值比较混乱
GET http://127.0.0.1:9501/index/demo?a=1

### 测试使用协程上下文的例子 a=1 输出"a": "1"
GET http://127.0.0.1:9501/index/demo1?a=1

### 测试数据库
GET http://127.0.0.1:9501/index/demodb

### 邮件发送
POST http://127.0.0.1:9501/auth/send-code?email=1131730668@qq.com
Accept: application/json
X-Language: ja

### 验证邮件
POST http://127.0.0.1:9501/auth/login?email=1131730668@qq.com&code=1234
Accept: application/json
X-Language: ja